name: Publish Docker Dev Image
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: udayantandon/d4sd-dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: BUILD_TYPE=dev
          tags: "latest"
      - name: Run Image on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker stop d4sd-dev
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rm d4sd-dev
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker image rm udayantandon/d4sd-dev:latest
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker pull udayantandon/d4sd-dev:latest
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker run -d -p 6000:80 --name d4sd-dev udayantandon/d4sd-dev:latest
